#pragma once

#include <JuceHeader.h>
#include <cstdint>

namespace gp200
{
class GP200ModSync final
{
  public:
    static void reloadIfChanged ();
    static bool replaceFromDevice (const juce::var& snapshot, int userIRSamples);
    static std::uint64_t getRevision ();

    static bool isCustomCloAmp (juce::uint32 effectId);
    static juce::String getDisplayName (juce::uint32 effectId);
    static juce::String getSourceFile (juce::uint32 effectId);
    static juce::String getDescription (juce::uint32 effectId);

    // PRE configurable mapping generated by the firmware HTML. These methods
    // are module-specific so duplicated PRE/DST IDs keep their stock meaning
    // outside PRE.
    static juce::uint32 getPreBankSourceEffectId (juce::uint32 preEffectId);
    static juce::String getPreBankDisplayName (juce::uint32 preEffectId);
    static juce::String getPreBankSourceModule (juce::uint32 preEffectId);
    static juce::String getPreBankDescription (juce::uint32 preEffectId);
    static juce::File getPreBankFile ();

    static void recordFactoryAmpOverride (juce::uint32 effectId,
                                          const juce::String& displayName,
                                          const juce::String& sourceFile);
    static void recordFactoryCabOverride (juce::uint32 effectId,
                                          const juce::String& displayName,
                                          const juce::String& sourceFile);

    static juce::File getManifestFile ();
};
} // namespace gp200
